### ISSUE TITLE
Infografía Contrato inteligente 

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-uzias10#1]
[Infografía Contrato inteligente.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-uzias10/files/8457678/Infografia.Contrato.inteligente.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo. Calificación: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
